jdr_fallout/fallout/urls.py
from django.urls import path
from .views import home, personnage, campagne

app_name = "fallout"

urlpatterns = [
    #path('login', login.login, name="Login"),
    path('', home.home, name="Home"),
    path('personnage/', personnage.list_all_personnage, name="list-personnage"),
    path('personnage/<int:pk>', personnage.display_personnage, name="detail-personnage"),
    path('personnage/create', personnage.create_personnage, name="create-personnage"),
    path('personnage/update/<int:pk>', personnage.update_personnage, name="update-personnage"),
    path('quest/', campagne.list_all_campagne, name="list-campagne"),
    path('quest/<int:pk>/', campagne.display_campagne, name="detail-campagne")
]

jdr_fallout/jdr_fallout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from fallout.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("fallout.urls", namespace="fallout")),
    path('logout', login.logout_view, name="logout_redirect"),
    path('account/', include("django.contrib.auth.urls"))
]

urlpatterns += staticfiles_urlpatterns()

jdr_fallout/fallout/models/aptitude.py
from django.db import models

from fallout.models.personnage import Personnage


class AptitudeModel(models.Model):
    """
    Aptitude model with all the fields.
    """
    name = models.CharField(max_length=100)
    nb_rangs = models.IntegerField(default=1)
    prerequis = models.JSONField()
    description = models.TextField(max_length=500)

    def __str__(self):
        return f"{self.name} [{self.nb_rangs}]"


class Aptitude(AptitudeModel):
    """
    Aptitude Class, to differ from the aptitude of the players.
    """


class AptitudeJoueur(AptitudeModel):
    """
    Aptitude class dedicated to a specific player.
    """
    proprietaire = models.ForeignKey(to=Personnage, on_delete=models.CASCADE)
    actual_rang = models.IntegerField(default=1)

jdr_fallout/fallout/models/campagne.py
from django.db import models


class Campagne(models.Model):
    """
    Class décrivant une campagne effectuée par des Personnages.
    """
    name = models.CharField(max_length=32)
    xp_point = models.IntegerField()

    # desc = models.CharField(max_length=32)

    def __str__(self):
        return self.name

jdr_fallout/fallout/models/effet_arme.py
from django.db import models


BRUTAL = "Brutal"
DEZONE = "De zone"
DESTRUCTEUR = "Destructeur"
ENRAFALE = "En rafale"
ETOURDISSANT = "Étourdissant"
PERFORANT = "Perforant"
PERSISTANT = "Persistant"
RADIOACTIF = "Radioactif"

LIST_EFFET_ARME = (
    BRUTAL,
    DEZONE,
    DESTRUCTEUR,
    ENRAFALE,
    ETOURDISSANT,
    PERFORANT,
    PERSISTANT,
    RADIOACTIF
)


class EffetArme(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name

jdr_fallout/fallout/models/item.py
from django.db import models
from django.core.validators import MinValueValidator


class Item(models.Model):
    name = models.CharField(max_length=100, null=True)
    poid = models.FloatField(validators=[MinValueValidator(0)], null=True)
    prix = models.IntegerField(validators=[MinValueValidator(0)], null=True)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True

jdr_fallout/fallout/models/personnage.py
from typing import List, Dict, Any

from django.db import models
from django.core.validators import MinValueValidator
from fallout.models.campagne import Campagne

# Déclaration des noms des origines
CONFRERIE_ACIER = "Confrérie de l'acier"
GOULE = "Goule"
SUPER_MUTANT = "Super mutant"
MISTER_HANDY = "Mister handy"
SURVIVANT = "Survivant"
HABITANT_ABRIS = "Habitant de l'abri"

# List origine pour lister les choix possibles à la création
LIST_ORIGINE = (
    (1, CONFRERIE_ACIER),
    (2, GOULE),
    (3, SUPER_MUTANT),
    (4, MISTER_HANDY),
    (5, SURVIVANT),
    (6, HABITANT_ABRIS)
)


class Personnage(models.Model):
    """
    Class de tous les personnages, joueurs et pnj.
    """
    name = models.CharField(max_length=200)
    origine = models.IntegerField(choices=LIST_ORIGINE, null=True)
    quest = models.ForeignKey(to=Campagne, null=True, blank=True, on_delete=models.CASCADE, default=None)
    level = models.IntegerField(default=1)
    xp = models.IntegerField(default=0)

    # S.P.E.C.I.A.L
    force = models.IntegerField(default=6, validators=[MinValueValidator(4)])
    perception = models.IntegerField(default=6, validators=[MinValueValidator(4)])
    endurance = models.IntegerField(default=6, validators=[MinValueValidator(4)])
    charisme = models.IntegerField(default=6, validators=[MinValueValidator(4)])
    intelligence = models.IntegerField(default=6, validators=[MinValueValidator(4)])
    agilite = models.IntegerField(default=6, validators=[MinValueValidator(4)])
    chance = models.IntegerField(default=6, validators=[MinValueValidator(4)])
    chance_point = models.IntegerField(default=0, validators=[MinValueValidator(4)])

    # PV max = Chance + Endurance
    pv_max = models.IntegerField(default=0)
    pv = models.IntegerField(default=0)

    # Bonus dégâts du joueur avec armes de corps à corps
    # Force 7-8 = 1
    # Force 9-10 = 2
    # Force 11+ = 3
    bonus_corps_a_corps = models.IntegerField(default=0)

    # Initiative = perception + agilite
    initiative = models.IntegerField(default=0)

    # Bonus defense
    # agilite <= 8 : 1
    # agilite >= 9 : 2
    bonus_defense = models.IntegerField(default=0)

    # Charge maximal = 75 + force x 5
    charge_maximal = models.IntegerField(default=0)

    # Résistance global au poison, ne concerne pas un membre en particulier
    resistance_poison = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    @property
    def get_pourcentage_health(self) -> float:
        """
        Get the pourcentage of health the player has remaining.

        :return: The pourcentage of health as (PV/MAX) * 100
        """
        return (self.pv / self.pv_max) * 100

    @property
    def get_attributes(self):
        attributes: Dict[str, Any] = {
            "S": self.force,
            "P": self.perception,
            "E": self.endurance,
            "C": self.charisme,
            "I": self.intelligence,
            "A": self.agilite,
        }
        return attributes

    @property
    def is_the_biggest(self) -> List[str]:
        """
        Get the list of the biggest attributes of a personnage.

        :return: The list of attribute that have the biggest value
        """
        attributes = self.get_attributes
        max_attributes = []
        max_value = 0
        for letter, attribute in attributes.items():
            if attribute > max_value:
                max_attributes = [letter]
                max_value = attribute
            elif attribute == max_value:
                max_attributes.append(letter)
        return max_attributes

    @property
    def get_experience_needed(self):
        """
        Calcul la quantité d'XP nécessaire au joueur pour monter de niveau.

        La quantité nécessaire est calculé par le calcul:
        (Niveau à atteindre x (Niveau actuel / 2)) x 100

        1 -> 2 : 100
        2 -> 3 : 300
        3 -> 4 : 600
        """
        actual_level = self.level
        next_level = actual_level + 1
        return (next_level * (actual_level / 2)) * 100


class Parti(models.Model):
    """
    Classe Partie, représente l'état d'une partie du
    corp d'un personnage (tête, bras, jambe et buste)
    Par défault, tous les membres ont une résistance de
    0 pour tous les types de dégâts.
    L'ajout d'armure/Tenue peut changer leurs valeurs.
    """

    class Position(models.IntegerChoices):
        TETE = 1
        BUSTE = 2
        BRAS_GAUCHE = 3
        BRAS_DROITE = 4
        JAMBE_GAUCHE = 5
        JAMBE_DROITE = 6

    personnage = models.ForeignKey(Personnage, on_delete=models.CASCADE)
    position = models.IntegerField(choices=Position.choices)
    resistance_balistique = models.IntegerField(default=0)
    resistance_energie = models.IntegerField(default=0)
    resistance_radiation = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.personnage.name} {self.get_position_display()}"


class Competence(models.Model):
    """
    Classe Compétence qui décrit la liste des compétences de tout les personnages.

    C'est cette liste qui va décrire l'efficacité des joueurs à effectuer certaines actions.
    Ex: Arme à Energie (PERCEPTION) : 2 
    Cela signifie que la compétence d'arme à énergie dépendant de l'attribut Perception
    et que le niveau de celui-ci est de niveau 2
    """

    class AttributDisplay(models.TextChoices):
        FORCE = "FOR"
        PERCEPTION = "PER"
        ENDURANCE = "END"
        CHARISME = "CHR"
        INTELLIGENCE = "INT"
        AGILITE = "AGI"

    class CompetenceName(models.TextChoices):
        ARME_ENERGIE = "Armes à énergie"
        ARME_CORPS = "Armes de corps à corps"
        ARME_LEGERES = "Armes légères"
        ARMES_LOURDES = "Armes lourdes"
        ATHLETISME = "Athlétisme"
        CROCHETAGE = "Crochetage"
        DISCOURS = "Discours"
        DISCRETION = "Discrétion"
        EXPLOSIFS = "Explosifs"
        MAIN_NUES = "Mains nues"
        MEDECINE = "Médecine"
        PILOTAGE = "Pilotage"
        PROJECTILES = "Projectiles"
        REPARATION = "Réparation"
        SCIENCES = "Sciences"
        SURVIE = "Survie"
        TROC = "Troc"
        OTHER = "Other"

    ASSOCIATION = {
        CompetenceName.ARME_ENERGIE: AttributDisplay.PERCEPTION,
        CompetenceName.ARME_CORPS: AttributDisplay.FORCE,
        CompetenceName.ARME_LEGERES: AttributDisplay.AGILITE,
        CompetenceName.ARMES_LOURDES: AttributDisplay.ENDURANCE,
        CompetenceName.ATHLETISME: AttributDisplay.FORCE,
        CompetenceName.CROCHETAGE: AttributDisplay.PERCEPTION,
        CompetenceName.DISCOURS: AttributDisplay.CHARISME,
        CompetenceName.DISCRETION: AttributDisplay.AGILITE,
        CompetenceName.EXPLOSIFS: AttributDisplay.PERCEPTION,
        CompetenceName.MAIN_NUES: AttributDisplay.FORCE,
        CompetenceName.MEDECINE: AttributDisplay.INTELLIGENCE,
        CompetenceName.PILOTAGE: AttributDisplay.PERCEPTION,
        CompetenceName.PROJECTILES: AttributDisplay.AGILITE,
        CompetenceName.REPARATION: AttributDisplay.INTELLIGENCE,
        CompetenceName.SCIENCES: AttributDisplay.INTELLIGENCE,
        CompetenceName.SURVIE: AttributDisplay.ENDURANCE,
        CompetenceName.TROC: AttributDisplay.CHARISME,
    }

    personnage = models.ForeignKey(Personnage, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, choices=CompetenceName.choices)
    attribut = models.CharField(max_length=3, choices=AttributDisplay.choices, null=True)
    is_atout_perso = models.BooleanField(default=False)
    rang = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f"{self.personnage.name}: {self.name} [{self.rang}]"

jdr_fallout/fallout/forms/personnage.py
from django.forms import ModelForm

from fallout.models.personnage import Personnage


class PersonnageForm(ModelForm):
    class Meta:
        model = Personnage
        fields = [
            "name",
            "origine",
            "force",
            "perception",
            "endurance",
            "charisme",
            "intelligence",
            "agilite",
            "chance",
        ]

jdr_fallout/fallout/views/campagne.py
from django.shortcuts import render
from fallout.models import Personnage, Competence, Campagne


def list_all_campagne(request):
    context = {"list_campagne": Campagne.objects.all()}
    return render(request=request, template_name="campagne/list_campagne.html", context=context)


def display_campagne(request, pk):
    campagne = Campagne.objects.get(id=pk)
    list_perso = Personnage.objects.filter(quest=campagne)
    context = {
        "campagne": campagne,
        "list_perso": list_perso
    }
    return render(request, 'campagne/display_campagne.html', context)

jdr_fallout/fallout/views/home.py
from django.shortcuts import render


def home(request):
    return render(request=request, template_name="home.html")

jdr_fallout/fallout/views/login.py
from django.shortcuts import redirect, render
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm


def login(request):
    context = {}
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            redirect("/")
    else:
        context['form'] = AuthenticationForm()
    return render(request=request, template_name="login.html", context=context)

def logout_view(request):
    logout(request)
    return redirect("login")

jdr_fallout/fallout/views/personnage.py
from django.shortcuts import render, redirect
from fallout.models import Personnage, Competence, Parti, ArmeDistante, Arme, TypeArme, Mods, Aptitude
from fallout.models.personnage import LIST_ORIGINE
from fallout.forms import PersonnageForm
from django.forms import modelformset_factory

from fallout.services import ServicePersonnage


def list_all_personnage(request):
    context = {"personnages": Personnage.objects.all()}
    return render(request=request, template_name="personnage/list_personnage.html", context=context)


def display_personnage(request, pk):
    personnage = Personnage.objects.get(pk=pk)
    list_competences = Competence.objects.filter(personnage=personnage)
    list_attributes = [
        personnage.force,
        personnage.perception,
        personnage.endurance,
        personnage.charisme,
        personnage.intelligence,
        personnage.agilite,
        personnage.chance
    ]
    list_parti = Parti.objects.filter(personnage=personnage)
    list_arme_distante = ArmeDistante.objects.filter(proprietaire=personnage)

    type_melee = [TypeArme.CORPSACORPS, TypeArme.EXPLOSIF, TypeArme.PROJECTILE]
    list_arme_melee = Arme.objects.filter(proprietaire=personnage, type__in=type_melee)
    list_mods = Mods.objects.filter(proprietaire=personnage)

    context = {
        "personnage": personnage,
        "list_competences": list_competences,
        "list_parti": list_parti,
        "list_arme_distante": list_arme_distante,
        "list_arme_melee": list_arme_melee,
        "list_mods": list_mods,
        "list_attributes": list_attributes
    }
    return render(request, 'personnage/display_personnage.html', context)


def create_personnage(request):
    if request.method == "POST":
        ServicePersonnage().create_new_personnage(request)
        return render(request, 'personnage/list_personnage.html', {'personnages': Personnage.objects.all()})

    form = PersonnageForm()
    aptitudes = {aptitude.id: {'name': aptitude.name, 'nb_rangs': aptitude.nb_rangs, 'prerequis': aptitude.prerequis,
                               'description': aptitude.description} for aptitude in Aptitude.objects.all()}
    origines = [origine for id, origine in LIST_ORIGINE]
    context = {'form': form, "competences": Competence.ASSOCIATION, "aptitudes": aptitudes, "origines": origines}
    return render(request=request, template_name="personnage/create_personnage.html", context=context)


def update_personnage(request, pk):
    personnage = Personnage.objects.get(pk=pk)
    competence_form_set = modelformset_factory(Competence, fields=['name', 'attribut', 'is_atout_perso', 'rang'], extra=0)

    if request.method == "POST":
        persoform = PersonnageForm(request.POST, instance=personnage)
        compform = competence_form_set(request.POST, queryset=Competence.objects.filter(personnage=personnage))
        for comp in compform:
            comp.fields["name"].disabled = True
            comp.fields["attribut"].disabled = True
        if all([persoform.is_valid(), compform.is_valid()]):
            personnage: Personnage = persoform.save()
            for c in compform:
                c.save()
            personnage.pv = personnage.endurance + personnage.chance
            match personnage.force:
                case num if 7 <= num <= 8:
                    personnage.bonus_corps_a_corps = 1
                case num if 9 <= num <= 10:
                    personnage.bonus_corps_a_corps = 2
                case num if num >= 11:
                    personnage.bonus_corps_a_corps = 3
            personnage.initiative = personnage.perception + personnage.agilite
            personnage.bonus_defense = 1 if personnage.agilite <= 8 else 2
            personnage.charge_maximal = 75 + personnage.force * 5
            personnage.chance_point = personnage.chance
            personnage.save()
            return redirect("/personnage/" + str(pk))
        else:
            print(persoform.errors.as_data())
            print(compform.errors)
            print(compform.error_messages)

    persoform = PersonnageForm(instance=personnage)
    compform = competence_form_set(queryset=Competence.objects.filter(personnage=personnage))
    for comp in compform:
        comp.fields["name"].disabled = True
        comp.fields["attribut"].disabled = True

    return render(request=request, template_name="personnage/modify_personnage.html",
                  context={'persoform': persoform, 'compform': compform})

jdr_fallout/fallout/templates/personnage/create_personnage.html
{% extends 'main.html' %}

{% block content %}


<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h1>Créer un personnage</h1>
        <p>Lorsque vous créez un personnage, vous devez effectuer certains choix concernant son origine, ses attributs S.P.E.C.I.A.L, ses compétences et ses aptitudes, puis calculer ses statistiques dérivées.</p>
        <div class="input-group mb-3 w-25">
            <input name="nom" id="nom_personnage" type="text" class="form-control form-control-lg w-25" placeholder="Nom du personnage" aria-label="Username" onfocusout="display_step_1()">
        </div>
        <div id="step_1" class="d-none">
            <hr>
            <h2>Étape 1 : Choisir son origine</h2>
            {% include "personnage/creation/step_1.html" %}
        </div>
        <div id="step_2" class="d-none">
            <hr>
            <h2>Étape 2 : Augmenter ses attributs S.P.E.C.I.A.L</h2>
            {% include "personnage/creation/step_2.html" %}
        </div>
        <div id="step_3" class="d-none">
            <hr>
            <h2>Étape 3 : Atouts personnels et achats de rangs de compétence</h2>
            {% include "personnage/creation/step_3.html" %}
        </div>
        <div id="step_4" class="d-none">
            <hr>
            <h2>Étape 4 : Choisir sa première aptitude</h2>
            {% include "personnage/creation/step_4.html" %}
        </div>
        <div id="step_5" class="d-none">
            <hr>
            <h2>Étape 5 : Statistique dérivées</h2>
            {% include "personnage/creation/step_5.html" %}
        </div>
        <hr>
        <input id="submit" type="submit" value="Submit" disabled/>
    </form>
</div>

{%  endblock content %}

jdr_fallout/fallout/templates/personnage/display_personnage.html
{% extends 'main.html' %}

{% block content %}

<div class="container-fluid sheet text-center">
	<div class="row">
		<div class="col-md-auto">
			<table class="table">
				<tr><td><div class="title">Nom du Personnage</div></td></tr>
				<tr><td><div class="body">{{personnage.name}}</div></tr></td>
			</table>
			<ul><li><a href="/personnage/update/{{personnage.id}}">Modify</a></li></ul>
		</div>
		<div class="col col-md-auto">
			<table class="table">
				<tr>
					<td><div class="title">XP Actuel</div></td>
					<td><div class="body">{{personnage.xp}}</div></td>
				</tr>
			</table>
			<table class="table">
				<tr>
					<td><div class="title">XP avant niveau sup</div></td>
					<td><div class="body">{{personnage.get_experience_needed}}</div></td>
				</tr>
			</table>
			<table class="table">
				<tr>
					<td><div class="title">Origine</div></td>
					<td><div class="body">{{personnage.get_origine_display}}</div></td>
				</tr>
			</table>
		</div>
		<div class="col col-md-auto position-relative h-100">
			<div class="gear">
				<div class="center"></div>
				<div class="tooth"></div>
				<div class="tooth"></div>
				<div class="tooth"></div>
				<div class="tooth"></div>
			</div>
			<div class="text">LVL {{personnage.level}}</div>
		</div>
	</div>
	<div class="row">
		<div class="col col-md-auto table-responsive-lg">
			<table class="table">
				<tr>
					<th><div class="label">S</div></th>
					<th><div class="label">P</div></th>
					<th><div class="label">E</div></th>
					<th><div class="label">C</div></th>
					<th><div class="label">I</div></th>
					<th><div class="label">A</div></th>
					<th><div class="label">L</div></th>
				</tr>
				<tr>
					{% for attribut in list_attributes %}
					<td>
						<div class="box-attribute">
							<div class="gear mini">
								<div class="center"></div>
								<div class="tooth"></div>
								<div class="tooth"></div>
								<div class="tooth"></div>
								<div class="tooth"></div>
							</div>
							<div class="text">{{ attribut }}</div>
						</div>
					</td>
					{% endfor %}
				</tr>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="table-responsive col col-md-auto">
			<table class="table table-hover">
				<tr>
					<th>Nom</th>
					<th>Atout</th>
					<th>Rang</th>
				</tr>
				{% for competence in list_competences %}
				<tr>
					<td>{{competence.name}} [{{competence.attribut}}]</td>
					<td>
						{% if competence.is_atout_perso %}
						<input type="checkbox" disabled="disabled" checked>
						{% else %}
						<input type="checkbox" disabled="disabled">
						{% endif %}
					</td>
					<td>{{competence.rang}}</td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col col-md-auto">
			<div class="row">
				<table class="table col right-space">
					<tr>
						<td><div class="title">PV max</div></td>
						<td><div class="body">{{personnage.pv_max}}</div></td>
					</tr>
				</table>
				<table class="table col right-space">
					<tr>
						<td><div class="title">PV actuels</div></td>
						<td><div class="body">{{personnage.pv}}</div></td>
					</tr>
				</table>
				<table class="table col right-space">
					<tr>
						<td><div class="title">Initiative</div></td>
						<td><div class="body">{{personnage.initiative}}</div></td>
					</tr>
				</table>
				<table class="table col right-space">
					<tr>
						<td><div class="title">Point de chance</div></td>
						<td><div class="body">{{personnage.chance_point}}</div></td>
					</tr>
				</table>
				<table class="table col right-space">
					<tr>
						<td><div class="title">Bonus de mêlée</div></td>
						<td><div class="body">{{personnage.bonus_corps_a_corps}}</div></td>
					</tr>
				</table>
				<table class="table col right-space">
					<tr>
						<td><div class="title">Défense</div></td>
						<td><div class="body">{{personnage.bonus_defense}}</div></td>
					<tr>
				</table>
			</div>
			<div class="row">
				{% for parti in list_parti %}
				<table class="table col right-space">
					<tr>
						<th colspan="2"><div class="title">{{parti.get_position_display}}</div></th>
					</tr>
					<tr>
						<td><div class="title">RD Bal</div></td>
						<td><div class="body">{{parti.resistance_balistique}}</div></td>
					</tr>
					<tr>
						<td><div class="title">RD Éne</div></td>
						<td><div class="body">{{parti.resistance_energie}}</div></td>
					</tr>
					<tr>
						<td><div class="title">RD Rad</div></td>
						<td><div class="body">{{parti.resistance_radiation}}</div></td>
					</tr>
				</table>
				{% endfor %}
			</div>
		</div>
	</div>
	<div class="row">
		{% include "personnage/inventaire/inventaire.html" %}
	</div>
</div>

{%  endblock content %}

jdr_fallout/fallout/templates/personnage/list_personnage.html
{% extends 'main.html' %}

{% block content %}

<a class="button btn btn-primary btn-lg" href="{% url 'fallout:create-personnage' %}" >Créer un Personnage</a>
<div class="table-responsive table-scroll text-center" data-mdb-perfect-scrollbar="true" style="position: relative; height: 700px">
  <table class="table table-dark mb-0">
      <h2>Liste des personnages</h2>
    <thead>
        <tr class="text-uppercase">
            <th scope="col">#</th>
            <th scope="col">Nom</th>
            <th scope="col">Origine</th>
            <th scope="col">LVL</th>
            <th scope="col">Campagne</th>
        </tr>
    </thead>
    <tbody>
    {% for personnage in personnages %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{{personnage.id}}">{{personnage.name}}</a></td>
        <td>{{personnage.get_origine_display}}</td>
        <td>{{personnage.level}}</td>
        <td>{% if personnage.quest %}<a href="/quest/{{personnage.quest.id}}">{{personnage.quest}}</a> {% else %} / {% endif %}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{%  endblock content %}

jdr_fallout/fallout/templates/personnage/modify_personnage.html
{% extends 'main.html' %}

{% block content %}

<h2>Modification</h2>

<div class="form">
    <form method="POST">
        {% csrf_token %}

        <div class="form-line">
            {{persoform.errors}}
            <label for="id_name">Nom</label>
            {{persoform.name}}
        </div>
        <div class="form-line">
            <label for="id_origine">Origine</label>
            {{persoform.origine}}
        </div>
        <div class="form-line">
            <label for="id_force">Force</label>
            {{persoform.force}}
        </div>
        <div class="form-line">
            <label for="id_perception">Perception</label>
            {{persoform.perception}}
        </div>
        <div class="form-line">
            <label for="id_endurance">Endurance</label>
            {{persoform.endurance}}
        </div>
        <div class="form-line">
            <label for="id_charisme">Charisme</label>
            {{persoform.charisme}}
        </div>
        <div class="form-line">
            <label for="id_intelligence">Intelligence</label>
            {{persoform.intelligence}}
        </div>
        <div class="form-line">
            <label for="id_agilite">Agilite</label>
            {{persoform.agilite}}
        </div>
        <div class="form-line">
            <label for="id_chance">Chance</label>
            {{persoform.chance}}
        </div>
		
		<div>
			<div>
				Compétences
			</div>
			<table>
				
				{{ compform.management_form }}
				 {% for competence in compform %}
					{{competence}}
				{% endfor %}
			</table>
		</div>

        <input type="submit" value="Submit" />
    </form>
</div>

{%  endblock content %}